[package]
name = "rooms"
version = "0.1.0"
authors = ["wasmcloud Team"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
wasmcloud-actor-core = { version = "0.2.2", features = ["guest"] }
wasmcloud-actor-logging = { version = "0.1.0", features = ["guest"]}
wasmcloud-actor-keyvalue = { version = "0.2.1", features = ["guest"] }
wasmcloudchat-rooms-interface = { path = "../../interface/rooms-interface"}
serde = { version = "1.0.123", features = ["derive"]}
serde_json = "1.0.64"
log = "0.4.14"


[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
