[package]
name = "pinger"
version = "0.1.0"
authors = ["wasmcloud Team"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
wasmcloud-actor-core = { version = "0.2.2", features = ["guest"] }
wasmcloud-actor-http-server = { version = "0.1.0", features = ["guest"]}
serde = { version = "1.0.123", features = ["derive"]}
ping-interface = { path = "../ping-interface"}

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
