[package]
name = "wasmcloudchat-presence-interface"
version = "0.1.0"
authors = ["wasmCloud Team"]
edition = "2018"
description = "Interface for interacting with the wasmcloud presence actor"

[dependencies]
wapc-guest = { version = "0.4.0"}
lazy_static = { version = "1.4.0"}

serde = { version = "1.0.123" , features = ["derive"] }
serde_json = "1.0.57"
serde_derive = "1.0.123"
serde_bytes = "0.11.5"
rmp-serde = "0.15.4"
log = { version="0.4.14", features =["std","serde"]}