[package]
name = "echo"
version = "0.2.2"
authors = ["wasmcloud Team"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = {version = "1.0.118", features = ["derive"]}
serde_json ="1.0.60"
wapc-guest = "0.4.0"
wasmcloud-actor-core = { version = "0.2.2", features = ["guest"] }
wasmcloud-actor-http-server = { version = "0.1.1", features = ["guest"]}

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
