[package]
name = "echo"
version = "0.0.2"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
actor-core = { git = "https://github.com/wascc/actor-interfaces", branch = "main" }
actor-http-server = { git = "https://github.com/wascc/actor-interfaces", branch = "main"}
serde_json ="1.0.60"
serde = {version = "1.0.118", features = ["derive"]}

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
