[package]
name = "telnet-channel"
version = "0.1.0"
authors = ["wasmcloud Team"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
log = "0.4.14"
wasmcloud-actor-core = { version = "0.2.2", features = ["guest"] }
wasmcloud-actor-logging = { version = "0.1.1", features = ["guest"] }
wasmcloud-actor-messaging = { version = "0.1.1", features = ["guest"] }

[dependencies.wasmcloud-actor-telnet]
version = "0.1.2"
features = ["guest"]
#path = "../../../../actor-interfaces/telnet/rust"

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
