[package]
name = "extras"
version = "0.2.1"
authors = ["wasmcloud Team"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
wasmcloud-actor-core = { version = "0.2.2", features = ["guest"]}
wasmcloud-actor-http-server = { version = "0.1.1", features = ["guest"]}
wasmcloud-actor-extras = { version = "0.1.1", features = ["guest"]}
serde_json = "1.0"

[profile.release]
# Optimize for small code size
opt-level = "s"