[package]
name = "fakepay-provider"
version = "0.1.0"
authors = ["wasmCloud Team"]
edition = "2018"


[features]
static_plugin = [] # Enable to statically compile this into a host

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
chrono = "0.4.19"
env_logger = "0.8.2"
log = "0.4.14"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
wascc-codec = "0.9.0"
payments-interface = { path = "../payments-interface" }
actor-core = { git = "https://github.com/wasmcloud/actor-interfaces", branch = "main" }
